import {readFile,readdir,stat} from 'node:fs/promises';
let DatabaseSync=null;try{({DatabaseSync}=await import('node:sqlite'));}catch{}
const DB_PATH='data/prices.sqlite3';
export let catalog={products:new Map(),stores:[],loadedAt:null,storage:null,databaseUpdatedAt:null};

async function filesFor(selected){const files=(await readdir('data/stores')).filter(file=>file.endsWith('.json')&&(selected===null||selected.includes(file.slice(0,-5))));return files.sort((a,b)=>Number(b.startsWith('shufersal'))-Number(a.startsWith('shufersal'))||a.localeCompare(b));}
async function currentDatabase(files){if(!DatabaseSync)return null;try{const dbStat=await stat(DB_PATH),storeStats=await Promise.all(files.map(file=>stat('data/stores/'+file)));return storeStats.every(s=>s.mtimeMs<=dbStat.mtimeMs)?dbStat:null;}catch{return null;}}
function whereIds(ids,column='s.id'){return ids===null?{sql:'',args:[]}:ids.length?{sql:` WHERE ${column} IN (${ids.map(()=>'?').join(',')})`,args:ids}:{sql:' WHERE 0',args:[]};}

async function loadSqlite(selected,dbStat){const products=new Map(),stores=[];const db=new DatabaseSync(DB_PATH,{readOnly:true});try{
 const storeWhere=whereIds(selected),storeRows=db.prepare(`SELECT * FROM stores s${storeWhere.sql} ORDER BY CASE WHEN chain='shufersal' THEN 0 ELSE 1 END,id`).all(...storeWhere.args);
 for(const s of storeRows)stores.push({id:s.id,chain:s.chain,chainName:s.chain_name,name:s.name,city:s.city,code:s.code,lastSuccessAt:s.last_success_at,error:s.error,portal:s.portal,count:s.product_count});
 const ids=storeRows.map(s=>s.id),promoWhere=whereIds(ids,'i.store_id'),promoMap=new Map();
 for(const row of db.prepare(`SELECT i.store_id,i.barcode,i.min_qty,i.max_qty,i.discounted_price,i.discount_rate,i.reward_type,p.promotion_id,p.description,p.starts_at,p.ends_at,p.club,p.coupon,p.restrictions,p.source_file,p.source_published_at FROM promotion_items i JOIN promotions p ON p.store_id=i.store_id AND p.promotion_id=i.promotion_id${promoWhere.sql}`).all(...promoWhere.args)){
  const key=row.store_id+'\u0000'+row.barcode;if(!promoMap.has(key))promoMap.set(key,[]);promoMap.get(key).push({id:row.promotion_id,description:row.description,start:row.starts_at,end:row.ends_at,club:row.club,coupon:Boolean(row.coupon),restrictions:row.restrictions,sourceFile:row.source_file,sourcePublishedAt:row.source_published_at,conditions:{barcode:row.barcode,minQty:row.min_qty,maxQty:row.max_qty,discountedPrice:row.discounted_price,discountRate:row.discount_rate,rewardType:row.reward_type}});
 }
 const offerWhere=whereIds(ids,'o.store_id');
 const rows=db.prepare(`SELECT p.id,p.barcode,p.name,p.brand,p.size,p.weighted,o.store_id,o.cents,o.unit,o.unit_price,o.price_updated_at,o.source_file,o.source_published_at,o.source_name,o.source_size,s.chain,s.chain_name,s.name AS store_name,s.city,s.last_success_at,s.portal,src.sha256,img.image_url,img.source_name AS image_source,img.source_page_url,img.license_name,img.license_url,img.attribution,img.source_updated_at AS image_updated_at,img.checked_at AS image_checked_at FROM offers o JOIN products p ON p.id=o.product_id JOIN stores s ON s.id=o.store_id LEFT JOIN sources src ON src.store_id=o.store_id AND src.file=o.source_file LEFT JOIN product_images img ON img.barcode=p.barcode AND img.status='verified'${offerWhere.sql} ORDER BY CASE WHEN s.chain='shufersal' THEN 0 ELSE 1 END,s.id,p.id`).all(...offerWhere.args);
 for(const row of rows){let product=products.get(row.id);if(!product){product={id:row.id,barcode:row.barcode,name:row.name,brand:row.brand,size:row.size,weighted:Boolean(row.weighted),image:row.image_url?{url:row.image_url,source:row.image_source,sourcePage:row.source_page_url,license:row.license_name,licenseUrl:row.license_url,attribution:row.attribution,updatedAt:row.image_updated_at,checkedAt:row.image_checked_at}:null,offers:[]};products.set(row.id,product);}product.offers.push({storeId:row.store_id,chain:row.chain,chainName:row.chain_name,storeName:row.store_name,city:row.city,cents:row.cents,unit:row.unit,unitPrice:row.unit_price,priceUpdatedAt:row.price_updated_at,sourceFile:row.source_file,sourcePublishedAt:row.source_published_at,lastCheckedAt:row.last_success_at,sourceUrl:row.portal,sourceHash:row.sha256,sourceName:row.source_name,sourceSize:row.source_size,promotions:promoMap.get(row.store_id+'\u0000'+row.barcode)||[]});}
 }finally{db.close();}
 catalog={products,stores,loadedAt:new Date().toISOString(),storage:'sqlite',databaseUpdatedAt:new Date(dbStat.mtimeMs).toISOString()};return catalog;}

async function loadJson(files){const products=new Map(),stores=[];for(const file of files){const s=JSON.parse(await readFile('data/stores/'+file,'utf8'));if(!s.products)continue;stores.push({id:s.id,chain:s.chain,chainName:s.chainName,name:s.name,city:s.city,code:s.code,lastSuccessAt:s.lastSuccessAt,error:s.error,portal:s.portal,count:Object.keys(s.products).length});const promoMap=new Map();for(const promo of Object.values(s.promotions||{}))for(const item of promo.items){if(!promoMap.has(item.barcode))promoMap.set(item.barcode,[]);promoMap.get(item.barcode).push({...promo,items:undefined,conditions:item});}for(const p of Object.values(s.products)){let product=products.get(p.id);if(!product){product={id:p.id,barcode:p.barcode,name:p.name,brand:p.brand,size:p.size,weighted:p.weighted,image:null,offers:[]};products.set(p.id,product);}product.offers.push({storeId:s.id,chain:s.chain,chainName:s.chainName,storeName:s.name,city:s.city,cents:p.cents,unit:p.unit,unitPrice:p.unitPrice,priceUpdatedAt:p.priceUpdatedAt,sourceFile:p.sourceFile,sourcePublishedAt:p.sourcePublishedAt,lastCheckedAt:s.lastSuccessAt,sourceUrl:s.portal,sourceHash:s.sources[p.sourceFile]?.sha256,sourceName:p.name,sourceSize:p.size,promotions:promoMap.get(p.barcode)||[]});}}
 catalog={products,stores,loadedAt:new Date().toISOString(),storage:'json',databaseUpdatedAt:null};return catalog;}

export async function loadCatalog(selected=null){const files=await filesFor(selected),dbStat=await currentDatabase(files);if(dbStat){try{return await loadSqlite(selected,dbStat);}catch(e){console.warn('SQLite catalog unavailable; using verified JSON snapshots:',e.message);}}return loadJson(files);}
export function activePromos(offer,now=Date.now()){return offer.promotions.filter(p=>Date.parse(p.start)<=now&&Date.parse(p.end)>=now);}
export function isStale(publishedAt,now=Date.now()){const published=Date.parse(publishedAt);return !Number.isFinite(published)||published>now+15*60e3||now-published>48*3600e3;}
export function filteredProduct(p,selected){const offers=p.offers.filter(o=>!selected.length||selected.includes(o.storeId)).map(o=>({...o,promotions:activePromos(o),stale:isStale(o.sourcePublishedAt)})).sort((a,b)=>Number(a.stale)-Number(b.stale)||a.cents-b.cents);return {...p,offers};}
function currentOffers(p){return p.offers.filter(o=>!o.stale);}
function currentSpread(p){const offers=currentOffers(p);return offers.length>1?offers.at(-1).cents-offers[0].cents:0;}
export function listProducts({q='',stores=[],promos=false,sort='',offset=0,limit=30}={}){const tokens=q.toLowerCase().trim().split(/\s+/).filter(Boolean);let rows=[];for(const p of catalog.products.values()){if(!tokens.every(t=>[p.name,p.brand,p.barcode].join(' ').toLowerCase().includes(t)))continue;const v=filteredProduct(p,stores);if(!v.offers.length||promos&&!v.offers.some(o=>o.promotions.length))continue;rows.push(v);}const featured=['7290004131074','7290004127329','8076800195057'];rows.sort((a,b)=>{if(sort==='price'){const ac=currentOffers(a)[0]?.cents??Infinity,bc=currentOffers(b)[0]?.cents??Infinity;return(Number.isFinite(ac)||Number.isFinite(bc)?ac-bc:0)||a.name.localeCompare(b.name,'he');}if(sort==='saving')return currentSpread(b)-currentSpread(a)||a.name.localeCompare(b.name,'he');const ai=featured.indexOf(a.barcode),bi=featured.indexOf(b.barcode);return (ai<0?999:ai)-(bi<0?999:bi)||b.offers.length-a.offers.length||a.name.localeCompare(b.name,'he');});return{total:rows.length,products:rows.slice(offset,offset+limit)};}
export function compareBasket(items,selected=[]){if(!Array.isArray(items)||items.length>100||!items.every(i=>typeof i.id==='string'&&Number.isInteger(i.quantity)&&i.quantity>=1&&i.quantity<=99))throw new Error('Invalid basket');const seen=new Set();for(const i of items){if(seen.has(i.id))throw new Error('Duplicate product');seen.add(i.id);}return catalog.stores.filter(s=>!selected.length||selected.includes(s.id)).map(s=>{let cents=0;const missing=[];let stale=false;for(const item of items){const p=catalog.products.get(item.id),o=p?.offers.find(o=>o.storeId===s.id);if(!o||p.weighted){missing.push(p?.name||item.id);continue;}cents+=o.cents*item.quantity;stale ||= isStale(o.sourcePublishedAt);}return{...s,cents,missing,complete:!missing.length&&items.length>0,stale};}).sort((a,b)=>Number(b.complete&&!b.stale)-Number(a.complete&&!a.stale)||Number(b.complete)-Number(a.complete)||a.cents-b.cents);}
