import {readFile,readdir} from 'node:fs/promises';
export let catalog={products:new Map(),stores:[],loadedAt:null};
export async function loadCatalog(selected=null){const products=new Map(),stores=[];for(const file of (await readdir('data/stores')).sort((a,b)=>Number(b.startsWith('shufersal'))-Number(a.startsWith('shufersal')))){if(!file.endsWith('.json')||selected&&!selected.includes(file.slice(0,-5)))continue;const s=JSON.parse(await readFile('data/stores/'+file,'utf8'));if(!s.products)continue;stores.push({id:s.id,chain:s.chain,chainName:s.chainName,name:s.name,city:s.city,code:s.code,lastSuccessAt:s.lastSuccessAt,error:s.error,portal:s.portal,count:Object.keys(s.products).length});const promoMap=new Map();for(const promo of Object.values(s.promotions||{}))for(const item of promo.items){if(!promoMap.has(item.barcode))promoMap.set(item.barcode,[]);promoMap.get(item.barcode).push({...promo,items:undefined,conditions:item});}
for(const p of Object.values(s.products)){let product=products.get(p.id);if(!product){product={id:p.id,barcode:p.barcode,name:p.name,brand:p.brand,size:p.size,weighted:p.weighted,offers:[]};products.set(p.id,product);}product.offers.push({storeId:s.id,chain:s.chain,chainName:s.chainName,storeName:s.name,city:s.city,cents:p.cents,unit:p.unit,unitPrice:p.unitPrice,priceUpdatedAt:p.priceUpdatedAt,sourceFile:p.sourceFile,sourcePublishedAt:p.sourcePublishedAt,lastCheckedAt:s.lastSuccessAt,sourceUrl:s.portal,sourceHash:s.sources[p.sourceFile]?.sha256,sourceName:p.name,sourceSize:p.size,promotions:promoMap.get(p.barcode)||[]});}}
catalog={products,stores,loadedAt:new Date().toISOString()};return catalog;}
export function activePromos(offer,now=Date.now()){return offer.promotions.filter(p=>Date.parse(p.start)<=now&&Date.parse(p.end)>=now);}
export function filteredProduct(p,selected){const offers=p.offers.filter(o=>!selected.length||selected.includes(o.storeId)).map(o=>({...o,promotions:activePromos(o),stale:Date.now()-Date.parse(o.sourcePublishedAt)>48*3600e3})).sort((a,b)=>a.cents-b.cents);return {...p,offers};}
export function listProducts({q='',stores=[],promos=false,sort='',offset=0,limit=30}={}){const tokens=q.toLowerCase().trim().split(/\s+/).filter(Boolean);let rows=[];for(const p of catalog.products.values()){if(!tokens.every(t=>[p.name,p.brand,p.barcode].join(' ').toLowerCase().includes(t)))continue;const v=filteredProduct(p,stores);if(!v.offers.length||promos&&!v.offers.some(o=>o.promotions.length))continue;rows.push(v);}const featured=['7290004131074','7290004127329','8076800195057'];rows.sort((a,b)=>{if(sort==='price')return a.offers[0].cents-b.offers[0].cents;if(sort==='saving')return(b.offers.at(-1).cents-b.offers[0].cents)-(a.offers.at(-1).cents-a.offers[0].cents);const ai=featured.indexOf(a.barcode),bi=featured.indexOf(b.barcode);return (ai<0?999:ai)-(bi<0?999:bi)||b.offers.length-a.offers.length||a.name.localeCompare(b.name,'he');});return{total:rows.length,products:rows.slice(offset,offset+limit)};}
export function compareBasket(items,selected=[]){if(!Array.isArray(items)||items.length>100||!items.every(i=>typeof i.id==='string'&&Number.isInteger(i.quantity)&&i.quantity>=1&&i.quantity<=99))throw new Error('Invalid basket');const seen=new Set();for(const i of items){if(seen.has(i.id))throw new Error('Duplicate product');seen.add(i.id);}return catalog.stores.filter(s=>!selected.length||selected.includes(s.id)).map(s=>{let cents=0;const missing=[];let stale=false;for(const item of items){const p=catalog.products.get(item.id),o=p?.offers.find(o=>o.storeId===s.id);if(!o||p.weighted){missing.push(p?.name||item.id);continue;}cents+=o.cents*item.quantity;stale ||= Date.now()-Date.parse(o.sourcePublishedAt)>48*3600e3;}return{...s,cents,missing,complete:!missing.length&&items.length>0,stale};}).sort((a,b)=>Number(b.complete)-Number(a.complete)||a.cents-b.cents);}
